import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
const sb=createClient('https://mkerawlqqtbknzeonnpt.supabase.co','sb_publishable_MMN9aLnhDDvShNccwtkXlw_hfF1upl4');const ID='BOOKCHAT-ADMIN';const go=p=>location.hash=p;
function Btn({children,secondary,onClick}){return <button className={'btn '+(secondary?'secondary':'')} onClick={onClick}>{children}</button>}
function Field({label,type='text',value,onChange}){return <label className="field"><b>{label}</b><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Login({setSession}){const[email,setEmail]=useState(''),[pw,setPw]=useState(''),[err,setErr]=useState('');async function submit(e){e.preventDefault();setErr('');const r=await sb.auth.signInWithPassword({email,password:pw});if(r.error)return setErr(r.error.message);const role=await sb.from('bookchat_admin_roles').select('role').eq('user_id',r.data.user.id).maybeSingle();if(!role.data){await sb.auth.signOut();return setErr('This account is not authorized for the admin console.')}setSession(r.data.user);go('#/admin/dashboard')}return <main className="auth"><form className="card"><div className="brand"><span>A</span><div><strong>BOOKCHAT ADMIN</strong><small>{ID}</small></div></div><h1>Control Center</h1><p>Separate administrator website. Regular users are rejected.</p><Field label="Admin email" type="email" value={email} onChange={setEmail}/><Field label="Password" type="password" value={pw} onChange={setPw}/>{err&&<div className="error">{err}</div>}<Btn onClick={submit}>Sign in</Btn></form></main>}
function Shell({active,setSession,children}){const nav=[['dashboard','Dashboard'],['users','Users'],['reports','Reports'],['moderation','Moderation'],['system','System'],['security','Security']];return <div className="shell"><aside><div className="brand"><span>A</span><div><strong>BOOKCHAT ADMIN</strong><small>Control Center</small></div></div><nav>{nav.map(x=><button className={active===x[0]?'active':''} onClick={()=>go('#/admin/'+x[0])} key={x[0]}>{x[1]}</button>)}</nav><button className="logout" onClick={async()=>{await sb.auth.signOut();setSession(null);go('#/admin/login')}}>Sign out</button></aside><main className="main"><header><div><small>{ID}</small><h1>{nav.find(x=>x[0]===active)?.[1]}</h1></div></header>{children}</main></div>}
function Dashboard(){const[c,setC]=useState({users:0,reports:0,groups:0,chats:0});useEffect(()=>{Promise.all([sb.from('bookchat_profiles').select('*',{count:'exact',head:true}),sb.from('bookchat_reports').select('*',{count:'exact',head:true}),sb.from('bookchat_groups').select('*',{count:'exact',head:true}),sb.from('bookchat_chats').select('*',{count:'exact',head:true})]).then(([a,b,d,e])=>setC({users:a.count||0,reports:b.count||0,groups:d.count||0,chats:e.count||0}))},[]);return <><div className="stats">{Object.entries(c).map(([k,v])=><div className="stat" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><section className="card"><h2>System status</h2><p>Supabase connected. BookChat user and admin applications are deployed as separate entrypoints.</p><span className="pill">RLS protected</span></section></>}
function Users(){const[rows,setRows]=useState([]);useEffect(()=>{sb.from('bookchat_profiles').select('id,full_name,username,email,school,department,updated_at').order('updated_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]))},[]);return <section className="card"><h2>Users</h2>{rows.length?rows.map(u=><div className="row" key={u.id}><span className="avatar">{(u.full_name||'U')[0]}</span><div><b>{u.full_name||'Unnamed'}</b><small>{u.email||u.username||'No email'} · {u.school||'No school'}</small></div></div>):<p>No users yet.</p>}</section>}
function Reports(){const[rows,setRows]=useState([]);async function load(){const{data}=await sb.from('bookchat_reports').select('*').order('created_at',{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);async function update(id,status){await sb.from('bookchat_reports').update({status,resolved_at:new Date().toISOString()}).eq('id',id);load()}return <section className="card"><h2>Reports & moderation</h2>{rows.length?rows.map(r=><div className="report" key={r.id}><div><b>{r.reason}</b><small>{r.details||'No details'}</small></div><Btn secondary onClick={()=>update(r.id,'DISMISSED')}>Dismiss</Btn><Btn onClick={()=>update(r.id,'RESOLVED')}>Resolve</Btn></div>):<p>No reports.</p>}</section>}
function System({security=false}){return <section className="card"><h2>{security?'Security':'System'}</h2><div className="health"><b>Supabase</b><span>Connected</span></div><div className="health"><b>RLS</b><span>Enabled on BookChat tables</span></div><div className="health"><b>Admin authorization</b><span>bookchat_admin_roles required</span></div><div className="health"><b>Frontend key</b><span>Publishable key only</span></div></section>}
function App(){const[hash,setHash]=useState(location.hash||'#/admin/login');const[session,setSession]=useState(null);useEffect(()=>{const f=()=>setHash(location.hash||'#/admin/login');addEventListener('hashchange',f);sb.auth.getSession().then(async({data})=>{if(data.session){const r=await sb.from('bookchat_admin_roles').select('role').eq('user_id',data.session.user.id).maybeSingle();if(r.data)setSession(data.session)}});return()=>removeEventListener('hashchange',f)},[]);if(!session)return <Login setSession={setSession}/>;const active=hash.split('/')[2]||'dashboard';let body=active==='users'?<Users/>:active==='reports'||active==='moderation'?<Reports/>:active==='security'?<System security/>:active==='system'?<System/>:<Dashboard/>;return <Shell active={active} setSession={setSession}>{body}</Shell>}
createRoot(document.getElementById('root')).render(<App/>);